# Generated by Django 3.2.7 on 2021-10-20 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_tipo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cardapio',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tipo',
            table='cardapio',
        ),
    ]
