# Generated by Django 3.2.7 on 2021-10-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_auto_20211019_2149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tipo',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='status',
            field=models.CharField(choices=[('bebida', 'bebida'), ('comida', 'comida'), ('', '')], default='', max_length=255),
        ),
        migrations.AlterModelTable(
            name='cardapio',
            table='cardapio',
        ),
    ]
