# Generated by Django 3.2.7 on 2021-10-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_auto_20211019_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='status',
            field=models.CharField(choices=[('bebida', 'bebida'), ('comida', 'comida')], max_length=255),
        ),
    ]
