# Generated by Django 3.2.7 on 2021-10-20 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_alter_cardapio_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardapio',
            old_name='status',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='item',
            name='id_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.cardapio', verbose_name='Receita'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.produto', verbose_name='Ingrediente'),
        ),
    ]
