# Generated by Django 3.2.7 on 2021-10-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sub_pedido_cdp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_pedido',
            name='cdp',
        ),
        migrations.AlterField(
            model_name='sub_pedido',
            name='id',
            field=models.IntegerField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
